name: Sync Docker Image

on:
  workflow_dispatch: # 允许手动触发
    inputs:
      source_image:
        description: '源镜像地址 (例如: registry.k8s.io/kube-apiserver:v1.27.4)'
        required: true
        type: string
      target_registry:
        description: '选择目标镜像仓库'
        required: true
        type: choice
        options:
          - ccr.ccs.tencentyun.com

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 根据选择的目标仓库动态登录
      - name: Login to Target Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ github.event.inputs.target_registry }}
          username: ${{ secrets.TENCENTYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.TENCENTYUN_REGISTRY_PASSWORD }}

      # 使用 skopeo 进行镜像同步
      - name: Sync Image with Skopeo
        run: |
          # 从源地址中提取镜像名和Tag，用于生成目标地址
          IMAGE_NAME=$(echo "${{ github.event.inputs.source_image }}" | awk -F'/' '{print $NF}')
          TARGET_IMAGE="${{ github.event.inputs.target_registry }}/${{ secrets.TENCENTYUN_REGISTRY_NAMESPACE }}/${IMAGE_NAME}"
          
          echo "正在同步: ${{ github.event.inputs.source_image }} -> $TARGET_IMAGE"
          skopeo copy --all docker://${{ github.event.inputs.source_image }} docker://$TARGET_IMAGE
